name: customrig
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  eva_icons_flutter: ^3.0.2
  firebase_core: ^1.15.0
  firebase_dynamic_links: ^4.2.1
  flutter:
    sdk: flutter
  intl: ^0.17.0
  ionicons: ^0.1.2
  open_file: ^3.2.1
  path_provider: ^2.0.10
  pdf: ^3.8.0
  permission_handler: ^9.2.0
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  share_plus: ^4.0.4
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
